version: '3'

services:
  postgis:
    image: postgis/postgis:15-3.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: cruise
      PGDATA: /var/lib/postgresql/data

    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - backend

  geoserver:
    image: geoserver/geoserver
    restart: always
    ports:
      - 8080:8080
    environment:
      GEOSERVER_DATA_DIR: /opt/geoserver/data_dir
      GEOSERVER_ADMIN_PASSWORD: your_geoserver_admin_password
    volumes:
      - ./geoserver_data:/opt/geoserver/data_dir