# Base image with PostgreSQL and PostGIS
FROM  geonode/postgis:15.3-latest


# Copy your custom pg_hba.conf into the container
#COPY pg_hba.conf /etc/postgresql/16/main/pg_hba.conf

# Ensure correct permissions
#RUN chown postgres:postgres /etc/postgresql/16/main/pg_hba.conf

# Expose the PostgreSQL port
EXPOSE 5432

# Ensure the PostgreSQL service runs with the specified configuration
#CMD ["postgres", "-c", "config_file=/etc/postgresql/16/main/postgresql.conf"]
