# Generated by Django 5.0.3 on 2024-04-02 05:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_type', models.CharField(max_length=10)),
                ('list_desc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('vessel_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('vessel_name', models.CharField(max_length=200)),
                ('vessel_desc', models.TextField()),
                ('vessel_picture', models.TextField()),
                ('vessel_credit_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cruise',
            fields=[
                ('cruise_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('iso2_country', models.CharField(max_length=2)),
                ('cruise_name', models.CharField(max_length=200)),
                ('cruise_desc', models.TextField()),
                ('cruise_data', models.TextField()),
                ('cruise_website_url', models.TextField()),
                ('cruise_doi_url', models.TextField()),
                ('cruise_status_id', models.IntegerField()),
                ('cruise_ship_name', models.CharField(max_length=100)),
                ('cruise_ship_flag', models.CharField(max_length=2)),
                ('cruise_ship_url', models.TextField()),
                ('cruise_ship_phone_contact', models.CharField(max_length=50)),
                ('cruise_ship_email_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('is_multi', models.BooleanField(default=False)),
                ('img_vessel_path', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruises.vessel')),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('leg_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('leg_number', models.IntegerField()),
                ('departure_port', models.CharField(max_length=50)),
                ('return_port', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='cruises.cruise')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('eez', models.CharField(blank=True, max_length=2, null=True)),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='cruises.cruise')),
            ],
        ),
        migrations.CreateModel(
            name='Scientist',
            fields=[
                ('scientist_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('is_chief_scientist', models.BooleanField(default=False)),
                ('email_contact', models.CharField(max_length=200)),
                ('phone_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('cruise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientists', to='cruises.cruise')),
            ],
        ),
    ]
