# Generated by Django 5.0.3 on 2024-07-25 05:35

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CruiseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Cruise status',
                'verbose_name_plural': 'Cruise status',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='cruise',
            options={'ordering': ['cruise_name'], 'verbose_name': 'Cruise', 'verbose_name_plural': 'Cruises'},
        ),
        migrations.AlterModelOptions(
            name='leg',
            options={'ordering': ['start_date'], 'verbose_name': 'Leg', 'verbose_name_plural': 'Legs'},
        ),
        migrations.AlterModelOptions(
            name='reflist',
            options={'ordering': ['list_type'], 'verbose_name': 'Reference List', 'verbose_name_plural': 'Reference Lists'},
        ),
        migrations.AlterModelOptions(
            name='scientist',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Scientist', 'verbose_name_plural': 'Scientists'},
        ),
        migrations.AlterModelOptions(
            name='vessel',
            options={'ordering': ['vessel_name'], 'verbose_name': 'Vessel', 'verbose_name_plural': 'Vessels'},
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='cruise_data',
        ),
        migrations.RemoveField(
            model_name='cruise',
            name='cruise_status_id',
        ),
        migrations.RemoveField(
            model_name='position',
            name='eez',
        ),
        migrations.AddField(
            model_name='position',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='cruise_desc',
            field=models.TextField(verbose_name='Cruise Description'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='cruise_doi_url',
            field=models.URLField(verbose_name='Cruise DOI URL'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='cruise_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='cruise_name',
            field=models.CharField(max_length=200, verbose_name='Cruise Name'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='cruise_ship_email_contact',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Cruise Ship Email Contact'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='cruise_ship_flag',
            field=models.CharField(max_length=2, verbose_name='Cruise Ship Flag'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='cruise_ship_name',
            field=models.CharField(max_length=100, verbose_name='Cruise Ship Name'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='cruise_ship_phone_contact',
            field=models.CharField(max_length=50, verbose_name='Cruise Ship Phone Contact'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='cruise_ship_url',
            field=models.URLField(verbose_name='Cruise Ship URL'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='cruise_website_url',
            field=models.URLField(verbose_name='Cruise Website URL'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='img_vessel_path',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='cruise_images/', verbose_name='Image Vessel Path'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='is_multi',
            field=models.BooleanField(default=False, verbose_name='Is Multi-Leg'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='iso2_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Associated User'),
        ),
        migrations.AlterField(
            model_name='cruise',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cruises.vessel', verbose_name='Associated Vessel'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='cruise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='cruises.cruise', verbose_name='Associated Cruise'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='departure_port',
            field=models.CharField(max_length=50, verbose_name='Departure Port'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='leg_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='leg',
            name='leg_number',
            field=models.IntegerField(verbose_name='Leg Number'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='return_port',
            field=models.CharField(max_length=50, verbose_name='Return Port'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reflist',
            name='list_desc',
            field=models.CharField(max_length=50, verbose_name='List Description'),
        ),
        migrations.AlterField(
            model_name='reflist',
            name='list_type',
            field=models.CharField(max_length=10, verbose_name='List Type'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='cruise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scientists', to='cruises.cruise', verbose_name='Associated Cruise'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='email_contact',
            field=models.EmailField(max_length=200, verbose_name='Email Contact'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='is_chief_scientist',
            field=models.BooleanField(default=False, verbose_name='Is Chief Scientist'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='phone_contact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Contact'),
        ),
        migrations.AlterField(
            model_name='scientist',
            name='scientist_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='vessel_credit_url',
            field=models.URLField(verbose_name='Vessel Credit URL'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='vessel_desc',
            field=models.TextField(verbose_name='Vessel Description'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='vessel_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='vessel_name',
            field=models.CharField(max_length=200, verbose_name='Vessel Name'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='vessel_picture',
            field=models.ImageField(max_length=10000, upload_to='vessel_images/', verbose_name='Vessel Picture'),
        ),
        migrations.AddField(
            model_name='cruise',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cruises.cruisestatus', verbose_name='Cruise Status'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, geography=True, null=True, srid=4326)),
                ('cruise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='cruises.cruise')),
            ],
        ),
    ]
