# Generated by Django 5.0.3 on 2024-08-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0002_cruisestatus_alter_cruise_options_alter_leg_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cruise',
            name='is_dirty',
            field=models.BooleanField(default=False),
        ),
    ]
