# Generated by Django 5.0.3 on 2024-08-04 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0003_cruise_is_dirty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cruise',
            name='is_dirty',
        ),
    ]
