# Generated by Django 5.0.3 on 2024-08-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0004_remove_cruise_is_dirty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['name'], 'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.AddField(
            model_name='route',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Route Color'),
        ),
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Route Description'),
        ),
        migrations.AddField(
            model_name='route',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='route',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Route Length (km)'),
        ),
        migrations.AddField(
            model_name='route',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Route Name'),
        ),
        migrations.AddField(
            model_name='route',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
