# Generated by Django 5.0.7 on 2024-08-05 01:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruises', '0007_alter_route_options_position_coordinates_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='path',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
