from django.urls import path, include
"""
URL configuration for the Pacific Cruises application.

This module sets up the URL routing for the `cruises` app using Django REST framework's `DefaultRouter`.
It registers the following viewsets:
- CruiseViewSet: Handles CRUD operations for Cruise objects.
- ScientistViewSet: Handles CRUD operations for Scientist objects.
- CruiseStatusViewSet: Handles CRUD operations for CruiseStatus objects.

The urlpatterns list includes the routes generated by the router.

Routes:
- /cruises/
- /scientists/
- /statuses/
"""
from rest_framework.routers import DefaultRouter
from .views import CruiseViewSet, ScientistViewSet, CruiseStatusViewSet

router = DefaultRouter()
router.register(r'cruises', CruiseViewSet)
router.register(r'scientists', ScientistViewSet)
router.register(r'statuses', CruiseStatusViewSet)

urlpatterns = [
    path('', include(router.urls)),
]
